### ISSUE TITLE
Using AzureServiceTokenProvider to authenticate with the Azure Libraries for .NET

### ISSUE THREAD

**Issue by kamiyn** [Azure/azure-docs-sdk-dotnet#961] opened 2019-04-04 06:44 UTC
I tried AzureServiceTokenProvider described in
https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication
to authenticate with the Azure Libraries for .NET
and it works as shown below.

If this approach is appropriate, please add it at https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate.

```cs
var tenantId = "tenantId (or directory Id) of your Azure Active Directory";
var azureServiceTokenProvider = new AzureServiceTokenProvider();
var token = await azureServiceTokenProvider.GetAccessTokenAsync("https://management.azure.com", tenantId);
var tokenCredentials = new TokenCredentials(token);
var azure = Azure
    .Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
    .Authenticate(new AzureCredentials(
        tokenCredentials,
        tokenCredentials,
        tenantId,
        AzureEnvironment.AzureGlobalCloud))
    .WithDefaultSubscription();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0ed2dc-fd93-c2e2-ecc7-0a1f7ce10c62
* Version Independent ID: 44070167-c751-c3da-b787-0240850690f4
* Content: [Authenticate with the Azure libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate?view=azure-dotnet)
* Content Source: [docs-ref-conceptual/dotnet-sdk-azure-authenticate.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-conceptual/dotnet-sdk-azure-authenticate.md)
* Service: **multiple**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by kamiyn** [comment] 2019-04-04 06:54
This code works with managed identities for App Service and Azure Functions works
https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity
without clientSecret or file-based authentication.

**Comment by jstutson** [comment] 2019-07-16 17:32
After working with the AzureServiceTokenProvider in other Azure SDK's I was wondering why AzureCredentials did not have support for it.  Thank you @kamiyn for this snippet but for whatever reason, my version of Microsoft.Azure.Management.ResourceManager.Fluent (v1.23.0) does not have an AzureCredentials constructor which accepts TokenCredentials.  So, I'm unable to reproduce your example.

**Comment by jstutson** [comment] 2019-07-16 18:22
I discovered the issue was I was using "TokenCredential," which I was previously using from Microsoft.Azure.Storage.Auth used in Storage Account AD auth instead of TokenCredentials from Microsoft.Rest.ClientRuntime::Microsoft.Rest.

**Comment by AtOMiCNebula** [comment] 2020-02-13 22:07
One suggestion for the code snippet: I think `TokenCredentials` needs two different tokens, not the same token twice.  One is a token for the `https://management.azure.com/` resource, and the other should be for `https://graph.windows.net/`.  I suspect that if the solution above works well for you, it's just not trying to use "both".

```csharp
string tenantId = "...";
AzureServiceTokenProvider tokenProvider = new AzureServiceTokenProvider();
IResourceManager resourceManager = ResourceManager
    .Authenticate(new AzureCredentials(
        new TokenCredentials(tokenProvider.GetAccessTokenAsync("https://management.azure.com/").Result),
        new TokenCredentials(tokenProvider.GetAccessTokenAsync("https://graph.windows.net/").Result),
        tenantId,
        AzureEnvironment.AzureGlobalCloud))
    .WithDefaultSubscription();
```

**Comment by Rookian** [comment] 2020-05-04 11:40
The proposed solutions work. Please make them available at https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate as @kamiyn suggested.

**Comment by jsquire** [comment] 2021-03-11 22:01
The source of this content has moved to the main MS Docs repository.   I've transferred this issue to [#23287](https://github.com/dotnet/docs/issues/23287);  closing this instance.

**Closed by jsquire** 2021-03-11 22:01 UTC
Labels: P1, Pri2, multiple/svc
