### ISSUE TITLE
What exactly does the prefetchCount parameter control?

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-docs-sdk-dotnet#633] opened 2018-05-14 19:09 UTC
There is absolutely no documentation on *any* of the constructor parameters, but the value of this parameter in particular is impossible (for me at least) to decipher as the name is too abstract to draw any specific conclusions from. It appears to me that this ends up setting `AmqpLinkSettings::TotalLinkCredit`, but that's an internal detail and, as such, there's no documentation on that either. 

NOTE: I also submitted feedback on the `PrefetchCount` property since that too is undocumented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 267bd24c-3558-cf09-4af7-21cdea4f4d6d
* Version Independent ID: f6d0f47f-6791-bb86-802c-da18926e2994
* Content: [AmqpTransportSettings Constructor (Microsoft.Azure.Devices.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.amqptransportsettings.-ctor?view=azure-dotnet#Microsoft_Azure_Devices_Client_AmqpTransportSettings__ctor_Microsoft_Azure_Devices_Client_TransportType_System_UInt32_)
* Content Source: [xml/Microsoft.Azure.Devices.Client/AmqpTransportSettings.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Client/AmqpTransportSettings.xml)
* Service: **iot-hub**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment] 2018-05-14 21:18
@fsautomata @dominicbetts Can you please help me find some information for @drub0y?

Thank you!

**Comment by yzhong94** [comment] 2018-05-15 14:57
@zolvarga @abhipsaMisra can you help with this question?

**Comment by CamSoper** [comment] 2018-06-21 00:44
Ping @zolvarga @abhipsaMisra @yzhong94

**Comment by CamSoper** [comment] 2018-07-05 21:04
Appears to be dupe of https://github.com/Azure/azure-docs-sdk-dotnet/issues/632

**Closed by CamSoper** 2018-07-05 21:04 UTC
Labels: question, requires-product-dev
