### ISSUE TITLE
 Speech Services SDK .NET  - 'factory.EndpointURL' threw an exception of type 'System.UriFormatException'

### ISSUE THREAD

**Issue by jaypaddy** [Azure/azure-docs-sdk-dotnet#715] opened 2018-07-17 03:58 UTC
Following through the Speech Services SDK .NET Console App for Windows, ran into issues at runtime with uriFormatException. the call is as follows

 var factory = SpeechFactory.FromSubscription($"{SUBKey}", "westus");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 565622df-0927-675e-3991-294963521d57
* Version Independent ID: 7056da5b-59cb-3790-65dc-bc089f8d5ca7
* Content: [SpeechFactory.EndpointURL Property (Microsoft.CognitiveServices.Speech)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechfactory.endpointurl?view=azure-dotnet)
* Content Source: [xml/Microsoft.CognitiveServices.Speech/SpeechFactory.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.CognitiveServices.Speech/SpeechFactory.xml)
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by mahilleb-msft** [comment] 2018-07-17 13:23
@jaypaddy - I think we can close the issue here, as we are handling this in the Speech SDK Samples repository, https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/22 ?

**Comment by CamSoper** [comment] 2018-07-19 23:14
Thanks for reporting this!  Closing as duplicate of https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/22.

**Closed by CamSoper** 2018-07-19 23:14 UTC
Labels: duplicate
