### ISSUE TITLE
Description display error

### ISSUE THREAD

**Issue by LucasDvp** [Azure/azure-docs-sdk-dotnet#614] opened 2018-05-03 03:00 UTC
Des display error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70eac671-6bea-b29e-84c1-65345f34e60c
* Version Independent ID: f9baa465-b63b-38dc-e13a-140d4a76cddd
* Content: [IEventProcessor Interface (Microsoft.Azure.EventHubs.Processor)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor.ieventprocessor?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.EventHubs.Processor/IEventProcessor.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.EventHubs.Processor/IEventProcessor.xml)
* Service: **event-hubs**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment] 2018-07-02 22:56
Duplicate of https://github.com/Azure/azure-docs-sdk-dotnet/issues/615

**Closed by CamSoper** 2018-07-02 22:56 UTC
Labels: doc-bug, duplicate
