### ISSUE TITLE
Strange formatting of interface descriptions

### ISSUE THREAD

**Issue by YegorK** [Azure/azure-docs-sdk-dotnet#690] opened 2018-06-26 18:27 UTC
Parts of interface descriptions are formatted as snippets and show raw HTML tags in them. Shouldn't they be formatted as normal text above them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1385cc44-bcdf-97e1-14f8-05dae39c3e5b
* Version Independent ID: 84f32302-2baa-bc4b-c210-cd777c22b428
* Content: [Microsoft.Azure.EventHubs.Processor Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor?view=azure-dotnet)
* Content Source: [xml/ns-Microsoft.Azure.EventHubs.Processor.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.Azure.EventHubs.Processor.xml)
* Service: **event-hubs**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment] 2018-07-02 23:10
Thanks for reporting this!

Closing as a duplicate of https://github.com/Azure/azure-docs-sdk-dotnet/issues/615

**Closed by CamSoper** 2018-07-02 23:10 UTC
