### ISSUE TITLE
Raw HTML visible on docs page

### ISSUE THREAD

**Issue by darthwalsh** [Azure/azure-docs-sdk-dotnet#932] opened 2019-02-02 17:29 UTC
On the docs page https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.appserviceplanpatchresource.isxenon?view=azure-dotnet the descriptions says

    ... service plan &lt;code&gt;true&lt;/code&gt;, &lt;code&gt;false&lt;/code&gt; otherwise.

I'm guessing the problem isn't with `IsXenon` but instead multiple layers are escaping HTML in docs?

**Comment by CamSoper** [comment] 2019-05-06 23:13
Duplicate of https://github.com/Azure/azure-docs-sdk-dotnet/issues/615

**Closed by CamSoper** 2019-05-06 23:13 UTC
Labels: doc-bug, xml-docs
